<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiaChiTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO `diachis` (`id`, `idtinh`, `ten`, `hoatdong`, `ghichu`) VALUES
                            (1, NULL, 'An Giang', b'1', NULL),
                            (2, NULL, 'Bà Rịa-Vũng Tàu', b'1', NULL),
                            (3, NULL, 'Bạc Liêu', b'1', NULL),
                            (4, NULL, 'Bắc Kạ', b'1', NULL),
                            (5, NULL, 'Bắc Giang', b'1', NULL),
                            (6, NULL, 'Bắc Ninh', b'1', NULL),
                            (7, NULL, 'Bến Tre', b'1', NULL),
                            (8, NULL, 'Bình Dương', b'1', NULL),
                            (9, NULL, 'Bình Định', b'1', NULL),
                            (10, NULL, 'Bình Phước', b'1', NULL),
                            (11, NULL, 'Bình Thuận', b'1', NULL),
                            (12, NULL, 'Cà Mau', b'1', NULL),
                            (13, NULL, 'Cao Bằng', b'1', NULL),
                            (14, NULL, 'Cần Thơ (TP)', b'1', NULL),
                            (15, NULL, 'Đà Nẵng (TP)', b'1', NULL),
                            (16, NULL, 'Đắk Lắk', b'1', NULL),
                            (17, NULL, 'Đắk Nông', b'1', NULL),
                            (18, NULL, 'Điện Biê', b'1', NULL),
                            (19, NULL, 'Đồng Nai', b'1', NULL),
                            (20, NULL, 'Đồng Tháp', b'1', NULL),
                            (21, NULL, 'Gia Lai', b'1', NULL),
                            (22, NULL, 'Hà Giang', b'1', NULL),
                            (23, NULL, 'Hà Nam', b'1', NULL),
                            (24, NULL, 'Hà Nội (TP)', b'1', NULL),
                            (26, NULL, 'Hà Tĩnh', b'1', NULL),
                            (27, NULL, 'Hải Dương', b'1', NULL),
                            (28, NULL, 'Hải Phòng (TP)', b'1', NULL),
                            (29, NULL, 'Hòa Bình', b'1', NULL),
                            (30, NULL, 'Hồ Chí Minh (TP)', b'1', NULL),
                            (31, NULL, 'Hậu Giang', b'1', NULL),
                            (32, NULL, 'Hưng Yê', b'1', NULL),
                            (33, NULL, 'Khánh Hòa', b'1', NULL),
                            (34, NULL, 'Kiên Giang', b'1', NULL),
                            (35, NULL, 'Kon Tum', b'1', NULL),
                            (36, NULL, 'Lai Châu', b'1', NULL),
                            (37, NULL, 'Lào Cai', b'1', NULL),
                            (38, NULL, 'Lạng Sơ', b'1', NULL),
                            (39, NULL, 'Lâm Đồng', b'1', NULL),
                            (40, NULL, 'Long A', b'1', NULL),
                            (41, NULL, 'Nam Định', b'1', NULL),
                            (42, NULL, 'Nghệ A', b'1', NULL),
                            (43, NULL, 'Ninh Bình', b'1', NULL),
                            (44, NULL, 'Ninh Thuậ', b'1', NULL),
                            (45, NULL, 'Phú Thọ', b'1', NULL),
                            (46, NULL, 'Phú Yê', b'1', NULL),
                            (47, NULL, 'Quảng Bình', b'1', NULL),
                            (48, NULL, 'Quảng Nam', b'1', NULL),
                            (49, NULL, 'Quảng Ngãi', b'1', NULL),
                            (50, NULL, 'Quảng Ninh', b'1', NULL),
                            (51, NULL, 'Quảng Trị', b'1', NULL),
                            (52, NULL, 'Sóc Trăng', b'1', NULL),
                            (53, NULL, 'Sơn La', b'1', NULL),
                            (54, NULL, 'Tây Ninh', b'1', NULL),
                            (55, NULL, 'Thái Bình', b'1', NULL),
                            (56, NULL, 'Thái Nguyê', b'1', NULL),
                            (57, NULL, 'Thanh Hóa', b'1', NULL),
                            (58, NULL, 'Thừa Thiên - Huế', b'1', NULL),
                            (59, NULL, 'Tiền Giang', b'1', NULL),
                            (60, NULL, 'Trà Vinh', b'1', NULL),
                            (61, NULL, 'Tuyên Quang', b'1', NULL),
                            (62, NULL, 'Vĩnh Long', b'1', NULL),
                            (63, NULL, 'Vĩnh Phúc', b'1', NULL),
                            (64, NULL, 'Yên Bái', b'1', NULL),
                            (65, 1, 'An Phú', b'0', NULL),
                            (66, 1, 'Châu Đốc', b'1', NULL),
                            (67, 1, 'Châu Phú', b'1', NULL),
                            (68, 1, 'Châu Thành', b'1', NULL),
                            (69, 1, 'Chợ Mới', b'1', NULL),
                            (70, 1, 'Long Xuyê', b'1', NULL),
                            (71, 1, 'Phú Tâ', b'1', NULL),
                            (72, 1, 'Tân Châu', b'1', NULL),
                            (73, 1, 'Thoại Sơ', b'1', NULL),
                            (74, 1, 'Tịnh Biê', b'1', NULL),
                            (75, 1, 'Tri Tô', b'1', NULL),
                            (76, 2, 'Côn Đảo', b'1', NULL),
                            (77, 2, 'Đất Đỏ', b'1', NULL),
                            (78, 2, 'Tân Thành', b'1', NULL),
                            (79, 2, 'Vũng Tàu', b'1', NULL),
                            (80, 2, 'Xuyên Mộc', b'1', NULL),
                            (81, 2, 'Bà Rịa', b'1', NULL),
                            (82, 2, 'Châu Đức', b'1', NULL),
                            (83, 2, 'Long Điề', b'1', NULL),
                            (84, 8, 'Bàu Bàng', b'1', NULL),
                            (85, 8, 'Bắc Tân Uyê', b'1', NULL),
                            (86, 8, 'Bến Cát Bình', b'1', NULL),
                            (87, 8, 'Dầu Tiếng', b'1', NULL),
                            (88, 8, 'Dĩ A', b'1', NULL),
                            (89, 8, 'Phú Giáo', b'1', NULL),
                            (90, 8, 'Tân Uyê', b'1', NULL),
                            (91, 8, 'TX. Thủ Dầu Một', b'1', NULL),
                            (92, 8, 'Thuận A', b'1', NULL),
                            (93, 10, 'Bình Long', b'1', NULL),
                            (94, 10, 'Bù Đăng', b'1', NULL),
                            (95, 10, 'Bù Đốp', b'1', NULL),
                            (96, 10, 'Bù Gia Mập', b'1', NULL),
                            (97, 10, 'Chơn Thành', b'1', NULL),
                            (98, 10, 'Đồng Phú', b'1', NULL),
                            (99, 10, 'Đồng Xoài', b'1', NULL),
                            (100, 10, 'Hớn Quả', b'1', NULL),
                            (101, 10, 'Lộc Ninh', b'1', NULL),
                            (102, 10, 'Phú Riềng', b'1', NULL),
                            (103, 10, 'Phước Long', b'1', NULL),
                            (104, 3, 'Đông Hải', b'1', NULL),
                            (105, 3, 'Giá Rai', b'1', NULL),
                            (106, 3, 'Hòa Bình', b'1', NULL),
                            (107, 3, 'Hồng Dâ', b'1', NULL),
                            (108, 3, 'Phước Long', b'1', NULL),
                            (109, 3, 'Vĩnh Lợi', b'1', NULL),
                            (110, 3, 'TP. Bạc Liêu', b'1', NULL),
                            (111, 4, 'Ba Bể', b'1', NULL),
                            (112, 4, 'Bạch Thông', b'1', NULL),
                            (113, 4, 'Chợ Đồ', b'1', NULL),
                            (114, 4, 'Chợ Mới', b'1', NULL),
                            (115, 4, 'Na Rì', b'1', NULL),
                            (116, 4, 'Ngân Sơ', b'1', NULL),
                            (117, 4, 'Pác Nặm', b'1', NULL),
                            (118, 4, 'TX. Bắc Kạ', b'1', NULL),
                            (119, 5, 'Hiệp Hòa', b'1', NULL),
                            (120, 5, 'Lạng Giang', b'1', NULL),
                            (121, 5, 'Lục Nam', b'1', NULL),
                            (122, 5, 'Lục Ngạ', b'1', NULL),
                            (123, 5, 'Sơn Động', b'1', NULL),
                            (124, 5, 'Tân Yê', b'1', NULL),
                            (125, 5, 'Việt Yê', b'1', NULL),
                            (126, 5, 'Yên Dũng', b'1', NULL),
                            (127, 5, 'Yên Thế', b'1', NULL),
                            (128, 5, 'TP. Bắc Giang', b'1', NULL),
                            (129, 6, 'Gia Bình', b'1', NULL),
                            (130, 6, 'Lương Tài', b'1', NULL),
                            (131, 6, 'Quế Võ', b'1', NULL),
                            (132, 6, 'Thuận Thành', b'1', NULL),
                            (133, 6, 'Tiên Du', b'1', NULL),
                            (134, 6, 'Yên Phong', b'1', NULL),
                            (135, 6, 'TP. Bắc Ninh', b'1', NULL),
                            (136, 6, 'TX. Từ Sơ', b'1', NULL),
                            (137, 7, 'Ba Tri', b'1', NULL),
                            (138, 7, 'Bình Đại', b'1', NULL),
                            (139, 7, 'Châu Thành', b'1', NULL),
                            (140, 7, 'Chợ Lách', b'1', NULL),
                            (141, 7, 'Giồng Trôm', b'1', NULL),
                            (142, 7, 'Mỏ Cày Bắc', b'1', NULL),
                            (143, 7, 'Mỏ Cày Nam', b'1', NULL),
                            (144, 7, 'Thanh Phúc', b'1', NULL),
                            (145, 7, 'TP. Bến Tre', b'1', NULL),
                            (146, 9, 'An Lão', b'1', NULL),
                            (147, 9, 'An Nhơ', b'1', NULL),
                            (148, 9, 'Hoài Â', b'1', NULL),
                            (149, 9, 'Hoài Nhơ', b'1', NULL),
                            (150, 9, 'Phù Mỹ', b'1', NULL),
                            (151, 9, 'Phù Cát', b'1', NULL),
                            (152, 9, 'Tây Sơ', b'1', NULL),
                            (153, 9, 'Tuy Phước', b'1', NULL),
                            (154, 9, 'Vân Canh', b'1', NULL),
                            (155, 9, 'Vĩnh Thạnh', b'1', NULL),
                            (156, 9, 'TP. Quy Nhơ', b'1', NULL),
                            (157, 11, 'Đức Linh', b'1', NULL),
                            (158, 11, 'Bắc Bình', b'1', NULL),
                            (159, 11, 'Hàm Tâ', b'1', NULL),
                            (160, 11, 'Hàm Thuận Bắc', b'1', NULL),
                            (161, 11, 'Hàm Thuận Nam', b'1', NULL),
                            (162, 11, 'Phú Quí', b'1', NULL),
                            (163, 11, 'Tánh Linh', b'1', NULL),
                            (164, 11, 'Tuy Phong', b'1', NULL),
                            (165, 11, 'TP. Phan Thiết', b'1', NULL),
                            (166, 11, 'TX. La Gi', b'1', NULL),
                            (167, 12, 'Cái Nước', b'1', NULL),
                            (168, 12, 'Đầm Dơi', b'1', NULL),
                            (169, 12, 'Năm Că', b'1', NULL),
                            (170, 12, 'Ngọc Hiể', b'1', NULL),
                            (171, 12, 'Phú Tâ', b'1', NULL),
                            (172, 12, 'Thới Bình', b'1', NULL),
                            (173, 12, 'Trần Văn Thời', b'1', NULL),
                            (174, 12, 'U Minh', b'1', NULL),
                            (175, 12, 'TP. Cà Mau', b'1', NULL),
                            (176, 13, 'Bảo Lạc', b'1', NULL),
                            (177, 13, 'Bảo Lâm', b'1', NULL),
                            (178, 13, 'Hạ Lang', b'1', NULL),
                            (179, 13, 'Hà Quảng', b'1', NULL),
                            (180, 13, 'Hòa A', b'1', NULL),
                            (181, 13, 'Nguyên Bình', b'1', NULL),
                            (182, 13, 'Phục Hòa', b'1', NULL),
                            (183, 13, 'Quảng Uyê', b'1', NULL),
                            (184, 13, 'Thạch A', b'1', NULL),
                            (185, 13, 'Thông Nông', b'1', NULL),
                            (186, 13, 'Trà Lĩnh', b'1', NULL),
                            (187, 13, 'Trùng Khánh', b'1', NULL),
                            (188, 13, 'TX. Cao Bằng', b'1', NULL),
                            (189, 14, 'Trung tâm thành phố', b'1', NULL),
                            (190, 14, 'Cờ Đỏ', b'1', NULL),
                            (191, 14, 'Phong Điề', b'1', NULL),
                            (192, 14, 'Thới Lai', b'1', NULL),
                            (193, 14, 'Vĩnh Thạnh', b'1', NULL),
                            (194, 14, 'Bình Thủy', b'1', NULL),
                            (195, 14, 'Cái Răng', b'1', NULL),
                            (196, 14, 'Ninh Kiều', b'1', NULL),
                            (197, 14, 'Ô Mô', b'1', NULL),
                            (198, 14, 'Thốt Nốt', b'1', NULL),
                            (199, 15, 'Trung tâm thành phố', b'1', NULL),
                            (200, 15, 'Hòa Vang', b'1', NULL),
                            (201, 15, 'Hoàng Sa', b'1', NULL),
                            (202, 15, 'Cẩm Lệ', b'1', NULL),
                            (203, 15, 'Hải Châu', b'1', NULL),
                            (204, 15, 'Liên Chiểu', b'1', NULL),
                            (205, 15, 'Ngũ Hành Sơ', b'1', NULL),
                            (206, 15, 'Sơn Trà', b'1', NULL),
                            (207, 15, 'Thanh Khê', b'1', NULL),
                            (208, 46, 'H. Đông Hòa', b'1', NULL),
                            (209, 46, 'H. Đồng Xuâ', b'1', NULL),
                            (210, 46, 'H. Phú Hòa', b'1', NULL),
                            (211, 46, 'H. Sơn Hòa', b'1', NULL),
                            (212, 46, 'H. Sông Hinh', b'1', NULL),
                            (213, 46, 'H. Tây Hòa', b'1', NULL),
                            (214, 46, 'H. Tuy A', b'1', NULL),
                            (215, 46, 'TP. Tuy Hòa', b'1', NULL),
                            (216, 46, 'TX. Sông Cầu', b'1', NULL),
                            (217, 47, 'H. Bố Trạch', b'1', NULL),
                            (218, 47, 'H. Lệ Thủy', b'1', NULL),
                            (219, 47, 'H. Minh Hóa', b'1', NULL),
                            (220, 47, 'H. Quảng Ninh', b'1', NULL),
                            (221, 47, 'H. Quảng Trạch', b'1', NULL),
                            (222, 47, 'H. Tuyên Hóa', b'1', NULL),
                            (223, 47, 'TP. Đồng Hới', b'1', NULL),
                            (224, 48, 'H. Bắc Trà My', b'1', NULL),
                            (225, 48, 'H. Đại lộc', b'1', NULL),
                            (226, 48, 'H. Điện Bà', b'1', NULL),
                            (227, 48, 'H. Đông Giang', b'1', NULL),
                            (228, 48, 'H. Duy Xuyê', b'1', NULL),
                            (229, 48, 'H. Hiệp Đức', b'1', NULL),
                            (230, 48, 'H. Nam Giang', b'1', NULL),
                            (231, 48, 'H. Nam Trà My', b'1', NULL),
                            (232, 48, 'H. Nông Sơ', b'1', NULL),
                            (233, 48, 'H. Núi Thành', b'1', NULL),
                            (234, 48, 'H. Phú Ninh', b'1', NULL),
                            (235, 48, 'H. Phước Sơ', b'1', NULL),
                            (236, 48, 'H. Quế Sơ', b'1', NULL),
                            (237, 48, 'H. Tây Giang', b'1', NULL),
                            (238, 48, 'H. Thăng Bình', b'1', NULL),
                            (239, 48, 'H. Tiên Phước', b'1', NULL),
                            (240, 48, 'TP. Hội A', b'1', NULL),
                            (241, 48, 'TP. Tam Kỳ', b'1', NULL),
                            (242, 49, 'H. Ba Tơ', b'1', NULL),
                            (243, 49, 'H. Bình Sơ', b'1', NULL),
                            (244, 49, 'H. Đức Phổ', b'1', NULL),
                            (245, 49, 'H. Lý Sơ', b'1', NULL),
                            (246, 49, 'H. Minh Long', b'1', NULL),
                            (247, 49, 'H. Mộ Đức', b'1', NULL),
                            (248, 49, 'H. Nghĩa Hành', b'1', NULL),
                            (249, 49, 'H. Sơn Hà', b'1', NULL),
                            (250, 49, 'H. Sơn Tây', b'1', NULL),
                            (251, 49, 'H. Sơn Tịnh', b'1', NULL),
                            (252, 49, 'H. Tây Trà', b'1', NULL),
                            (253, 49, 'H. Trà Bồng', b'1', NULL),
                            (254, 49, 'H. Tư Nghĩa', b'1', NULL),
                            (255, 49, 'TP. Quảng Nghãi', b'1', NULL),
                            (256, 50, 'H. Ba Chẽ', b'1', NULL),
                            (257, 50, 'H. Bình Liêu', b'1', NULL),
                            (258, 50, 'H. Cô Tô', b'1', NULL),
                            (259, 50, 'H. Đầm Hà', b'1', NULL),
                            (260, 50, 'H. Đông Triều', b'1', NULL),
                            (261, 50, 'H. Hải Hà', b'1', NULL),
                            (262, 50, 'H. Hoành Bồ', b'1', NULL),
                            (263, 50, 'H. Tiên Yê', b'1', NULL),
                            (264, 50, 'H. Vân Đồ', b'1', NULL),
                            (265, 50, 'H. Yên Hưng', b'1', NULL),
                            (266, 50, 'TP. Hạ Long', b'1', NULL),
                            (267, 50, 'TP. Móng Cái', b'1', NULL),
                            (268, 50, 'TX. Cẩm Phả', b'1', NULL),
                            (269, 50, 'TX. Uông Bí', b'1', NULL),
                            (270, 40, 'Bến Lức', b'1', NULL),
                            (271, 40, 'Cần Đước', b'1', NULL),
                            (272, 40, 'Cần Giuộc', b'1', NULL),
                            (273, 40, 'Châu Thành', b'1', NULL),
                            (274, 40, 'Đức Hòa', b'1', NULL),
                            (275, 40, 'Đức Huệ', b'1', NULL),
                            (276, 40, 'Mộc Hóa', b'1', NULL),
                            (277, 40, 'Tân Hưng', b'1', NULL),
                            (278, 40, 'Tân Thạnh', b'1', NULL),
                            (279, 40, 'Thạnh Hóa', b'1', NULL),
                            (280, 40, 'Thủ Thừa', b'1', NULL),
                            (281, 40, 'Vĩnh Hưng', b'1', NULL),
                            (282, 40, 'TP.Tân A', b'1', NULL),
                            (283, 41, 'Giao Thủy', b'1', NULL),
                            (284, 41, 'Hải Hậu', b'1', NULL),
                            (285, 41, 'Mỹ Lộc', b'1', NULL),
                            (286, 41, 'Nam Trực', b'1', NULL),
                            (287, 41, 'Nghĩa Hưng', b'1', NULL),
                            (288, 41, 'Trực Ninh', b'1', NULL),
                            (289, 41, 'Vụ Bả', b'1', NULL),
                            (290, 41, 'Xuân Trưởng', b'1', NULL),
                            (291, 41, 'Ý Yê', b'1', NULL),
                            (292, 41, 'TP.Nam Định', b'1', NULL),
                            (293, 42, 'Anh Sơ', b'1', NULL),
                            (294, 42, 'Con Cuông', b'1', NULL),
                            (295, 42, 'Diễn Châu', b'1', NULL),
                            (296, 42, 'Đô Lương', b'1', NULL),
                            (297, 42, 'Kỳ Sơ', b'1', NULL),
                            (298, 42, 'Nam Đà', b'1', NULL),
                            (299, 42, 'Nghi Lộc', b'1', NULL),
                            (300, 42, 'Nghĩa Đà', b'1', NULL),
                            (301, 42, 'Quế Phong', b'1', NULL),
                            (302, 42, 'Quỳ Châu', b'1', NULL),
                            (303, 42, 'Quỳ Hợp', b'1', NULL),
                            (304, 42, 'Quỳnh Lưu', b'1', NULL),
                            (305, 42, 'Tân Kỳ', b'1', NULL),
                            (306, 42, 'Thanh Chương', b'1', NULL),
                            (307, 42, 'Yên Thành', b'1', NULL),
                            (308, 42, 'TP.Vinh', b'1', NULL),
                            (309, 42, 'TX.Cửa Lò', b'1', NULL),
                            (310, 42, 'TX.Thái Hòa', b'1', NULL),
                            (311, 43, 'Gia Viễ', b'1', NULL),
                            (312, 43, 'Hoa Lư', b'1', NULL),
                            (313, 43, 'Kim Sơ', b'1', NULL),
                            (314, 43, 'Nho Qua', b'1', NULL),
                            (315, 43, 'Yên Khánh', b'1', NULL),
                            (316, 43, 'Yên Mô', b'1', NULL),
                            (317, 43, 'TP.Nình Bình', b'1', NULL),
                            (318, 43, 'TX.Tam Hiệp', b'1', NULL),
                            (319, 44, 'Bác Ái', b'1', NULL),
                            (320, 44, 'Ninh Hải', b'1', NULL),
                            (321, 44, 'Ninh Phước', b'1', NULL),
                            (322, 44, 'Ninh Sơ', b'1', NULL),
                            (323, 44, 'Thuận Bắc', b'1', NULL),
                            (324, 44, 'Thuận Nam', b'1', NULL),
                            (325, 44, 'TP.Phan Rang- Tháp Chàm', b'1', NULL),
                            (326, 45, 'Cẩm Khê', b'1', NULL),
                            (327, 45, 'Đoan Hùng', b'1', NULL),
                            (328, 45, 'Hạ Hòa', b'1', NULL),
                            (329, 45, 'Lâm Thao', b'1', NULL),
                            (330, 45, 'Phù Ninh', b'1', NULL),
                            (331, 45, 'Tam Nông', b'1', NULL),
                            (332, 45, 'Tân Sơ', b'1', NULL),
                            (333, 45, 'Thanh Ba', b'1', NULL),
                            (334, 45, 'Thanh Sơ', b'1', NULL),
                            (335, 45, 'Thanh Thủy', b'1', NULL),
                            (336, 45, 'Yên Lập', b'1', NULL),
                            (337, 45, 'TP.Việt Trì', b'1', NULL),
                            (338, 45, 'TX.Phú Thọ', b'1', NULL),
                            (339, 63, 'TP. Vĩnh Yê', b'1', NULL),
                            (340, 63, 'Tam Dương', b'1', NULL),
                            (341, 63, 'Lập Thạch', b'1', NULL),
                            (342, 63, 'Vĩnh Tường', b'1', NULL),
                            (343, 63, 'Yên Lạc', b'1', NULL),
                            (344, 63, 'Bình Xuyê', b'1', NULL),
                            (345, 63, 'Mê Linh', b'1', NULL),
                            (346, 63, 'TX. Phúc Yê', b'1', NULL),
                            (347, 63, 'Tam Đảo', b'1', NULL),
                            (464, 61, 'Chiêm Hóa', b'1', NULL),
                            (465, 61, 'Hàm Yê', b'1', NULL),
                            (466, 61, 'Na Hang', b'1', NULL),
                            (467, 61, 'Sơn Dương', b'1', NULL),
                            (468, 61, 'Yên Sơ', b'1', NULL),
                            (469, 61, 'TP. Tuyên Quang', b'1', NULL),
                            (470, 62, 'Bình Minh', b'1', NULL),
                            (471, 62, 'Bình Tâ', b'1', NULL),
                            (472, 62, 'Long Hồ', b'1', NULL),
                            (473, 62, 'Mang Thít', b'1', NULL),
                            (474, 62, 'Tam Bình', b'1', NULL),
                            (475, 62, 'Trà Ô', b'1', NULL),
                            (476, 62, 'Vũng Liêm', b'1', NULL),
                            (477, 62, 'TP. Vĩnh Long', b'1', NULL),
                            (478, 21, 'TP. Pleiku', b'1', NULL),
                            (479, 21, 'TX. An Khê', b'1', NULL),
                            (480, 21, 'Ayun Pa', b'1', NULL),
                            (481, 21, 'Chư Păh', b'1', NULL),
                            (482, 21, 'Chư Prông', b'1', NULL),
                            (483, 21, 'Chư Sê', b'1', NULL),
                            (484, 21, 'Đắk Đoa', b'1', NULL),
                            (485, 22, 'Bắc Giang', b'1', NULL),
                            (486, 22, 'Đồng Vă', b'1', NULL),
                            (487, 22, 'Hoàng Su Phì', b'1', NULL),
                            (488, 22, 'Mèo Vạc', b'1', NULL),
                            (489, 22, 'Quản Bạ', b'1', NULL),
                            (490, 22, 'Vị Xuyê', b'1', NULL),
                            (491, 22, 'Xín Mầ', b'1', NULL),
                            (492, 22, 'Yên Minh', b'1', NULL),
                            (493, 23, 'TX. Phủ Lý', b'1', NULL),
                            (494, 23, 'Duy Tiê', b'1', NULL),
                            (495, 23, 'Kim Bảng', b'1', NULL),
                            (496, 23, 'Lý Nhâ', b'1', NULL),
                            (497, 23, 'Thanh Liêm', b'1', NULL),
                            (498, 23, 'Bình Lục', b'1', NULL),
                            (499, 24, 'Ba Đình', b'1', NULL),
                            (500, 24, 'Bắc Từ Liêm', b'1', NULL),
                            (501, 24, 'Cầu Giấy', b'1', NULL),
                            (502, 24, 'Đống Đa', b'1', NULL),
                            (503, 24, 'Hà Đông', b'1', NULL),
                            (504, 24, 'Hai Bà Trưng', b'1', NULL),
                            (505, 24, 'Hoàn Kiếm', b'1', NULL),
                            (506, 24, 'Hoàng Mã', b'1', NULL),
                            (507, 24, 'Long Biê', b'1', NULL),
                            (508, 24, 'Nam Từ Liêm', b'1', NULL),
                            (509, 24, 'Tây Hồ', b'1', NULL),
                            (510, 24, 'Thanh Xuâ', b'1', NULL),
                            (511, 24, 'Sơn Tây', b'1', NULL),
                            (512, 24, 'Ba Vì', b'1', NULL),
                            (513, 24, 'Chương Mĩ', b'1', NULL),
                            (514, 24, 'Đan Phượng', b'1', NULL),
                            (515, 24, 'Đông Anh', b'1', NULL),
                            (516, 24, 'Gia Lâm', b'1', NULL),
                            (517, 24, 'Hoài Đức', b'1', NULL),
                            (518, 24, 'Mê Linh', b'1', NULL),
                            (519, 24, 'Mỹ Đức', b'1', NULL),
                            (520, 24, 'Phú Xuyê', b'1', NULL),
                            (521, 24, 'Phú Thọ', b'1', NULL),
                            (522, 24, 'Quốc Oai', b'1', NULL),
                            (523, 24, 'Sóc Sơ', b'1', NULL),
                            (524, 24, 'Thạch Thất', b'1', NULL),
                            (525, 24, 'Thanh Oai', b'1', NULL),
                            (526, 24, 'Thanh Trì', b'1', NULL),
                            (527, 24, 'Thường Tí', b'1', NULL),
                            (528, 24, 'Từ Liêm', b'1', NULL),
                            (529, 24, 'Ứng Hòa', b'1', NULL),
                            (530, 36, 'Mường Tè', b'1', NULL),
                            (531, 36, 'Phong Thổ', b'1', NULL),
                            (532, 36, 'Sin Hồ', b'1', NULL),
                            (533, 36, 'Tam Ðường', b'1', NULL),
                            (534, 36, 'Tân Uyê', b'1', NULL),
                            (535, 36, 'Than Uyê', b'1', NULL),
                            (536, 36, 'TX.Lai Châu', b'1', NULL),
                            (537, 37, 'Bạc Hà', b'1', NULL),
                            (538, 37, 'Bảo Thượng', b'1', NULL),
                            (539, 37, 'Bao Yê', b'1', NULL),
                            (540, 37, 'Bát Xát', b'1', NULL),
                            (541, 37, 'Mường Khương', b'1', NULL),
                            (542, 37, 'Sa Pa', b'1', NULL),
                            (543, 37, 'Si Ma Cai', b'1', NULL),
                            (544, 37, 'Van Bà', b'1', NULL),
                            (545, 37, 'TP.Lào Cai', b'1', NULL),
                            (546, 38, 'Bảc So', b'1', NULL),
                            (547, 38, 'Bình Gia', b'1', NULL),
                            (548, 38, 'Cao Lộc', b'1', NULL),
                            (549, 38, 'Chi Lang', b'1', NULL),
                            (550, 38, 'Ðình Lập', b'1', NULL),
                            (551, 38, 'Hữu Lung', b'1', NULL),
                            (552, 38, 'Lộc Bình', b'1', NULL),
                            (553, 38, 'Tràng Định', b'1', NULL),
                            (554, 38, 'Van Lãng', b'1', NULL),
                            (555, 38, 'Van Qua', b'1', NULL),
                            (556, 38, 'TP.Lạng So', b'1', NULL),
                            (557, 39, 'Bảo Lâm', b'1', NULL),
                            (558, 39, 'Cát Tiê', b'1', NULL),
                            (559, 39, 'Ðô Huoai', b'1', NULL),
                            (560, 39, 'Ðam Rông', b'1', NULL),
                            (561, 39, 'Di Linh', b'1', NULL),
                            (562, 39, 'Ðon Duong', b'1', NULL),
                            (563, 39, 'Ðộc Trng', b'1', NULL),
                            (564, 39, 'Lạc Duong', b'1', NULL),
                            (565, 39, 'Lâm Hà', b'1', NULL),
                            (566, 39, 'TP.Bảo Lộc', b'1', NULL),
                            (567, 39, 'TP.Ðà Lạt', b'1', NULL),
                            (568, 16, 'Buôn Đô', b'1', NULL),
                            (569, 16, 'Cư Kui', b'1', NULL),
                            (570, 16, 'Cư Mgar', b'1', NULL),
                            (571, 16, 'Ea Kar', b'1', NULL),
                            (572, 16, 'Ea Súp', b'1', NULL),
                            (573, 16, 'EaHLeo', b'1', NULL),
                            (574, 16, 'Krông Ana', b'1', NULL),
                            (575, 16, 'Krông Búk', b'1', NULL),
                            (576, 16, 'Krông Năng', b'1', NULL),
                            (577, 16, 'Krông Pắc', b'1', NULL),
                            (578, 16, 'Lắk', b'1', NULL),
                            (579, 16, 'MDrắk', b'1', NULL),
                            (580, 16, 'TP.Buôn Ma Thuật', b'1', NULL),
                            (581, 16, 'TX.Buôn Hồ', b'1', NULL),
                            (582, 17, 'Cư Jút', b'1', NULL),
                            (583, 17, 'Đắk GLong', b'1', NULL),
                            (584, 17, 'Đắk Mil', b'1', NULL),
                            (585, 17, 'Đắk RLấp', b'1', NULL),
                            (586, 17, 'Đắk Song', b'1', NULL),
                            (587, 17, 'Krông Nô', b'1', NULL),
                            (588, 17, 'Tuy Đức', b'1', NULL),
                            (589, 17, 'TX.Gia Nghĩa', b'1', NULL),
                            (590, 18, 'Điện Biê', b'1', NULL),
                            (591, 18, 'Điện Biên Đông', b'1', NULL),
                            (592, 18, 'Mường Chà', b'1', NULL),
                            (593, 18, 'Mương Nhé', b'1', NULL),
                            (594, 18, 'Mường Ảng', b'1', NULL),
                            (595, 18, 'Tủa Chùa', b'1', NULL),
                            (596, 18, 'Tuần Giáo', b'1', NULL),
                            (597, 18, 'TP.Điện Biên Phủ', b'1', NULL),
                            (598, 18, 'TX.Mường Lay', b'1', NULL),
                            (599, 19, 'Cẩm Mỹ', b'1', NULL),
                            (600, 19, 'Định Quá', b'1', NULL),
                            (601, 19, 'Long Thành', b'1', NULL),
                            (602, 19, 'Nhơn Trạch', b'1', NULL),
                            (603, 19, 'Tân Phú', b'1', NULL),
                            (604, 19, 'Thống Nhất', b'1', NULL),
                            (605, 19, 'Vĩnh Cửu', b'1', NULL),
                            (606, 19, 'Xuân Lộc', b'1', NULL),
                            (607, 19, 'TP.Biên Hòa', b'1', NULL),
                            (608, 19, 'TX.Long Khánh', b'1', NULL),
                            (609, 20, 'Cao Lãnh', b'1', NULL),
                            (610, 20, 'Châu Thành', b'1', NULL),
                            (611, 20, 'Hồng Ngự', b'1', NULL),
                            (612, 20, 'Lai Vung', b'1', NULL),
                            (613, 20, 'Lấp Vò', b'1', NULL),
                            (614, 20, 'Tâm Nông', b'1', NULL),
                            (615, 20, 'Tân Hồng', b'1', NULL),
                            (616, 20, 'Thanh Bình', b'1', NULL),
                            (617, 20, 'Tháp Mười', b'1', NULL),
                            (618, 20, 'TP.Cao Lãnh', b'1', NULL),
                            (619, 20, 'TX.Hồng Ngự', b'1', NULL),
                            (620, 20, 'TX.Sa Đéc', b'1', NULL),
                            (621, 56, 'Đại Tử', b'1', NULL),
                            (622, 56, 'Định Hóa', b'1', NULL),
                            (623, 56, 'Đồng Hỷ', b'1', NULL),
                            (624, 56, 'Phổ Yê', b'1', NULL),
                            (625, 56, 'Phú Bình', b'1', NULL),
                            (626, 56, 'Phú Lương', b'1', NULL),
                            (627, 56, 'Võ Nhai', b'1', NULL),
                            (628, 56, 'TP.Thái Nguyê', b'1', NULL),
                            (629, 56, 'TX.Sông Công', b'1', NULL),
                            (630, 57, 'Bá Thước', b'1', NULL),
                            (631, 57, 'Cẩm Thúy', b'1', NULL),
                            (632, 57, 'Đông Sơ', b'1', NULL),
                            (633, 57, 'Hà Trung', b'1', NULL),
                            (634, 57, 'Hậu Lộc', b'1', NULL),
                            (635, 57, 'Hoằng Hóa', b'1', NULL),
                            (636, 57, 'Lang Chánh', b'1', NULL),
                            (637, 57, 'Mường Lát', b'1', NULL),
                            (638, 57, 'Nga Sơ', b'1', NULL),
                            (639, 57, 'Ngọc Lặc', b'1', NULL),
                            (640, 57, 'Như Thanh', b'1', NULL),
                            (641, 57, 'Như Xuâ', b'1', NULL),
                            (642, 57, 'Nông Cống', b'1', NULL),
                            (643, 57, 'Quan Hóa', b'1', NULL),
                            (644, 57, 'Quan Sơ', b'1', NULL),
                            (645, 57, 'Quảng Xương', b'1', NULL),
                            (646, 57, 'Thạch Thành', b'1', NULL),
                            (647, 57, 'Thiệu Hóa', b'1', NULL),
                            (648, 57, 'Thường Xuâ', b'1', NULL),
                            (649, 57, 'Thọ Xuâ', b'1', NULL),
                            (650, 57, 'Tĩnh Gia', b'1', NULL),
                            (651, 57, 'Triệu Sơ', b'1', NULL),
                            (652, 57, 'Vĩnh Lộc', b'1', NULL),
                            (653, 57, 'Yên Định', b'1', NULL),
                            (654, 57, 'TP.Thanh Hóa', b'1', NULL),
                            (655, 57, 'TX.Bỉm Sơ', b'1', NULL),
                            (656, 57, 'TX.Sầm Sơ', b'1', NULL),
                            (657, 58, 'A Lưới', b'1', NULL),
                            (658, 58, 'Hường Trà', b'1', NULL),
                            (659, 58, 'Nam Dông', b'1', NULL),
                            (660, 58, 'Phong Điề', b'1', NULL),
                            (661, 58, 'Phú Lộc', b'1', NULL),
                            (662, 58, 'Phú Vang', b'1', NULL),
                            (663, 58, 'Quang Điề', b'1', NULL),
                            (664, 58, 'TP.Huế', b'1', NULL),
                            (665, 58, 'TX.Hương Thủy', b'1', NULL),
                            (666, 59, 'Cái Bè', b'1', NULL),
                            (667, 59, 'Cai Lây', b'1', NULL),
                            (668, 59, 'Châu Thành', b'1', NULL),
                            (669, 59, 'Chợ Gạo', b'1', NULL),
                            (670, 59, 'Gò Công Đông', b'1', NULL),
                            (671, 59, 'Gò Công Tây', b'1', NULL),
                            (672, 59, 'Tân Phú Đông', b'1', NULL),
                            (673, 59, 'Tân Phước', b'1', NULL),
                            (674, 59, 'TP.Mỹ Tho', b'1', NULL),
                            (675, 59, 'TX.Gò Công', b'1', NULL),
                            (676, 60, 'Càng Long', b'1', NULL),
                            (677, 60, 'Cầu Kè', b'1', NULL),
                            (678, 60, 'Cầu Ngang', b'1', NULL),
                            (679, 60, 'Châu Thành', b'1', NULL),
                            (680, 60, 'Duyên Hải', b'1', NULL),
                            (681, 60, 'Tiểu Cầ', b'1', NULL),
                            (682, 60, 'Trà Cú', b'1', NULL),
                            (683, 60, 'TP.Trà Vinh', b'1', NULL),
                            (684, 26, 'Cẩm Xuyê', b'1', NULL),
                            (685, 26, 'Can Lộc', b'1', NULL),
                            (686, 26, 'Đức Thọ', b'1', NULL),
                            (687, 26, 'Hương Khê', b'1', NULL),
                            (688, 26, 'Hương Sơ', b'1', NULL),
                            (689, 26, 'Kỳ Anh', b'1', NULL),
                            (690, 26, 'Lộc Hà', b'1', NULL),
                            (691, 26, 'Nghi Xuâ', b'1', NULL),
                            (692, 26, 'Thạch Hà', b'1', NULL),
                            (693, 26, 'Vũ Quang', b'1', NULL),
                            (694, 26, 'TP. Hà Tĩnh', b'1', NULL),
                            (695, 26, 'TX. Hồng Lĩnh', b'1', NULL),
                            (696, 27, 'Bình Giang', b'1', NULL),
                            (697, 27, 'Cẩm Giàng', b'1', NULL),
                            (698, 27, 'Gia Lộc', b'1', NULL),
                            (699, 27, 'Kim Thành', b'1', NULL),
                            (700, 27, 'Kinh Mô', b'1', NULL),
                            (701, 27, 'Nam Sách', b'1', NULL),
                            (702, 27, 'Ninh Giang', b'1', NULL),
                            (703, 27, 'Thanh Hà', b'1', NULL),
                            (704, 27, 'Thanh Miệ', b'1', NULL),
                            (705, 27, 'Tứ Kỳ', b'1', NULL),
                            (706, 27, 'TP. Hải Dương', b'1', NULL),
                            (707, 27, 'TX. Chí Linh', b'1', NULL),
                            (708, 28, 'Trung tâm thành phố', b'1', NULL),
                            (709, 28, 'An Dương', b'1', NULL),
                            (710, 28, 'An Lão', b'1', NULL),
                            (711, 28, 'Bạch Long Vĩ', b'1', NULL),
                            (712, 28, 'Cát Hải', b'1', NULL),
                            (713, 28, 'Kiến Thụy', b'1', NULL),
                            (714, 28, 'Thủy Nguyê', b'1', NULL),
                            (715, 28, 'Tiên Lãng', b'1', NULL),
                            (716, 28, 'Vĩnh Bảo', b'1', NULL),
                            (717, 28, 'Đồ Sơ', b'1', NULL),
                            (718, 28, 'Dương Kính', b'1', NULL),
                            (719, 28, 'Hải A', b'1', NULL),
                            (720, 28, 'Hồng Bàng', b'1', NULL),
                            (721, 28, 'Kiến A', b'1', NULL),
                            (722, 28, 'Lê Châ', b'1', NULL),
                            (723, 28, 'Ngô Quyề', b'1', NULL),
                            (724, 28, 'Hải A', b'1', NULL),
                            (725, 29, 'Cao Phong', b'1', NULL),
                            (726, 29, 'Đà Bắc', b'1', NULL),
                            (727, 29, 'Kỳ Sơ', b'1', NULL),
                            (728, 29, 'Lạc Sơ', b'1', NULL),
                            (729, 29, 'Lạc Thủy', b'1', NULL),
                            (730, 29, 'Lương Sơ', b'1', NULL),
                            (731, 29, 'Mai Châu', b'1', NULL),
                            (732, 29, 'Tân Lạc', b'1', NULL),
                            (733, 29, 'Yên Thủy', b'1', NULL),
                            (734, 29, 'Hòa Bình', b'1', NULL),
                            (735, 30, 'Trung tâm thành phố', b'1', NULL),
                            (736, 30, 'Bình Chánh', b'1', NULL),
                            (737, 30, 'Cần Giờ', b'1', NULL),
                            (738, 30, 'Củ Chi', b'1', NULL),
                            (739, 30, 'Hóc Mô', b'1', NULL),
                            (740, 30, 'Nhà Bè', b'1', NULL),
                            (741, 30, 'Quận 1', b'1', NULL),
                            (742, 30, 'Quận 2', b'1', NULL),
                            (743, 30, 'Quận 3', b'1', NULL),
                            (744, 30, 'Quận 4', b'1', NULL),
                            (745, 30, 'Quận 5', b'1', NULL),
                            (746, 30, 'Quận 6', b'1', NULL),
                            (747, 30, 'Quận 7', b'1', NULL),
                            (748, 30, 'Quận 8', b'1', NULL),
                            (749, 30, 'Quận 9', b'1', NULL),
                            (750, 30, 'Quận 10', b'1', NULL),
                            (751, 30, 'Quận 11', b'1', NULL),
                            (752, 30, 'Quận 12', b'1', NULL),
                            (753, 30, 'Bình Tâ', b'1', NULL),
                            (754, 30, 'Bình Thạnh', b'1', NULL),
                            (755, 30, 'Gò Vấp', b'1', NULL),
                            (756, 30, 'Phú Nhuậ', b'1', NULL),
                            (757, 30, 'Tân Bình', b'1', NULL),
                            (758, 30, 'Tân Phú', b'1', NULL),
                            (759, 30, 'Thủ Đức', b'1', NULL),
                            (760, 31, 'Châu Thành', b'1', NULL),
                            (761, 31, 'Châu Thành A', b'1', NULL),
                            (762, 31, 'Long Mỹ', b'1', NULL),
                            (763, 31, 'Phụng Hiệp', b'1', NULL),
                            (764, 31, 'Vị Thủy', b'1', NULL),
                            (765, 31, 'TP. Vị Thanh', b'1', NULL),
                            (766, 31, 'TX. Ngã Bảy', b'1', NULL),
                            (767, 32, 'Ân Thi', b'1', NULL),
                            (768, 32, 'Khoái Châu', b'1', NULL),
                            (769, 32, 'Kim Động', b'1', NULL),
                            (770, 32, 'Mỹ Hào', b'1', NULL),
                            (771, 32, 'Phù Cừ', b'1', NULL),
                            (772, 32, 'Tiên Lữ', b'1', NULL),
                            (773, 32, 'Văn Giang', b'1', NULL),
                            (774, 32, 'Văn Lâm', b'1', NULL),
                            (775, 32, 'Yên Mỹ', b'1', NULL),
                            (776, 32, 'TP. Hưng Yê', b'1', NULL),
                            (777, 33, 'Cam Lâm', b'1', NULL),
                            (778, 33, 'Diên Khánh', b'1', NULL),
                            (779, 33, 'Khánh Sơ', b'1', NULL),
                            (780, 33, 'Khánh Vĩnh', b'1', NULL),
                            (781, 33, 'Ninh Hòa', b'1', NULL),
                            (782, 33, 'Trường Sa', b'1', NULL),
                            (783, 33, 'Vạn Ninh', b'1', NULL),
                            (784, 33, 'TP. Nha Trang', b'1', NULL),
                            (785, 33, 'TX. Cam Ranh', b'1', NULL),
                            (786, 34, 'An Biê', b'1', NULL),
                            (787, 34, 'An Minh', b'1', NULL),
                            (788, 34, 'Châu Thành', b'1', NULL),
                            (789, 34, 'Giang Thành', b'1', NULL),
                            (790, 34, 'Giồng Riềng', b'1', NULL),
                            (791, 34, 'Gò Quao', b'1', NULL),
                            (792, 34, 'Hòn Đất', b'1', NULL),
                            (793, 34, 'Kiên Hải', b'1', NULL),
                            (794, 34, 'Kiên Lương', b'1', NULL),
                            (795, 34, 'Phú Quốc', b'1', NULL),
                            (796, 34, 'Tân Hiệp', b'1', NULL),
                            (797, 34, 'U Minh Thượng', b'1', NULL),
                            (798, 34, 'Vĩnh Thuậ', b'1', NULL),
                            (799, 34, 'TP. Rạch Giá', b'1', NULL),
                            (800, 34, 'TX. Hà Tiê', b'1', NULL),
                            (801, 51, 'TP. Long Xuyê', b'1', NULL),
                            (802, 51, 'TP. Châu Đốc', b'1', NULL),
                            (803, 51, 'An Phú', b'1', NULL),
                            (804, 51, 'TX. Tân Châu', b'1', NULL),
                            (805, 51, 'Phú Tâ', b'1', NULL),
                            (806, 51, 'Tịnh Biê', b'1', NULL),
                            (807, 52, 'TP. Vũng Tàu', b'1', NULL),
                            (808, 52, 'TP. Bà Rịa', b'1', NULL),
                            (809, 52, 'Xuyên Mộc', b'1', NULL),
                            (810, 52, 'Long Điề', b'1', NULL),
                            (811, 53, 'TP. Mỹ Tho', b'1', NULL),
                            (812, 53, 'TP. Châu Đốc', b'1', NULL),
                            (813, 53, 'Thị xã Gò Công', b'1', NULL),
                            (814, 53, 'Cái Bè', b'1', NULL),
                            (815, 53, 'Cai Lậy', b'1', NULL),
                            (816, 53, 'Châu Thành', b'1', NULL),
                            (817, 53, 'Chợ Gạo', b'1', NULL),
                            (818, 53, 'Gò Công Tây', b'1', NULL),
                            (819, 53, 'Gò Công Đông', b'1', NULL),
                            (820, 53, 'Tân Phước', b'1', NULL),
                            (821, 53, 'Tân Phú Đông', b'1', NULL),
                            (822, 53, 'Thị xã Cai Lậy', b'1', NULL),
                            (823, 54, 'TP. Rạch Giá', b'1', NULL),
                            (824, 54, 'Thị xã Hà Tiê', b'1', NULL),
                            (825, 54, 'Kiên Lương', b'1', NULL),
                            (826, 54, 'Hòn Đất', b'1', NULL),
                            (827, 54, 'Tân Hiệp', b'1', NULL),
                            (828, 54, 'Châu Thành', b'1', NULL),
                            (829, 54, 'Giồng Riềng', b'1', NULL),
                            (830, 54, 'Gò Quao', b'1', NULL),
                            (831, 54, 'An Biê', b'1', NULL),
                            (832, 54, 'An Minh', b'1', NULL),
                            (833, 54, 'Vĩnh Thuậ', b'1', NULL),
                            (834, 54, 'Phú Quốc', b'1', NULL),
                            (835, 54, 'U Minh Thượng', b'1', NULL),
                            (836, 54, 'Giang Thành', b'1', NULL),
                            (837, 35, 'Đắk Glei', b'1', NULL),
                            (838, 35, 'Đắk Hà', b'1', NULL),
                            (839, 35, 'Đắk Tô', b'1', NULL),
                            (840, 35, 'Kon Plông', b'1', NULL),
                            (841, 35, 'Kon Rẫy', b'1', NULL),
                            (842, 35, 'Ngọc Hồi', b'1', NULL),
                            (843, 35, 'Sa Thầy', b'1', NULL),
                            (844, 35, 'Tu Mơ Rông', b'1', NULL),
                            (845, 35, 'TP. Kon Tum', b'1', NULL),
                            (846, 55, 'Đông Hưng', b'1', NULL),
                            (847, 55, 'Hưng Hà', b'1', NULL),
                            (848, 55, 'Kiến Xương', b'1', NULL),
                            (849, 55, 'Quỳnh Phụ', b'1', NULL),
                            (850, 55, 'Thái Thụy', b'1', NULL),
                            (851, 55, 'Tiền Hải', b'1', NULL),
                            (852, 55, 'Vũ Thư', b'1', NULL),
                            (853, 55, 'TP. Thái Bình', b'1', NULL),
                            (854, 64, 'Lục Yê', b'1', NULL),
                            (855, 64, 'Mù Cang Chải', b'1', NULL),
                            (856, 64, 'Trạm Tấu', b'1', NULL),
                            (857, 64, 'Trấn Yê', b'1', NULL),
                            (858, 64, 'Văn Chấ', b'1', NULL),
                            (859, 64, 'Văn Yê', b'1', NULL),
                            (860, 64, 'Yên Bình', b'1', NULL),
                            (861, 64, 'TP. Yên Bái', b'1', NULL),
                            (862, 64, 'TX. Nghĩa Lộ', b'1', NULL);");
    }
}
